---
title: "Advanced `git`"
author: "Jan Simson"
format:
  html:
    subtitle: "Course Materials for an Advanced One-Day Workshop"
    toc: true
    output-file: index.html
    theme: cosmo
    code-links:
      - text: Repository
        href: https://github.com/jansim/advanced-git
        icon: github
        target: _blank
  gfm:
    toc: false
    output-file: README.md
format-links: false
---

This repository contains the course materials for a one-day workshop titled "Advaned `git`", developed for the Scientific Computing Center (SCC) and Houce of Competence (HOC) at the Karlsruhe Institute of Technology (KIT).

<!--
  To update the README, render this file directly via
  quarto render README.qmd --to=gfm
-->

## Contents

### Slides

- Block 1: Intro, Recap & Merging
  - 1.0 Intro [[slides]](https://simson.io/advanced-git/1.0-intro.html)
  - 1.1 Basics of git [[slides]](https://simson.io/advanced-git/1.1-git-basics.html)
  - 1.2 History [[slides]](1.2-history.html)
  - 1.3 Branches & Merging [[slides]](1.3-branches_merging.html)
  - 1.4 Filters & Hooks [[slides]](1.4-filters_and_hooks.html)

- Block 2: Best Practices: Pull / Merge Requests, Trunk-Based Development
  - 2.1 Collaboration & Pull Requests [[slides]](https://simson.io/advanced-git/2.1-collaboration-pull-requests.html)
  - 2.2 Trunk Based Development [[slides]](https://simson.io/advanced-git/2.2-trunk-based-development.html)

- Block 3: CI / CD with GitHub
  - 3.1 GitHub CI / CD [[slides]](https://simson.io/advanced-git/3.1-github-CI-CD.html)

- Block 4: Stashes, Cherry Picking, Patches & more
  - 4.1 Advanced Features of git [[slides]](https://simson.io/advanced-git/4.1-advanced-features.html)
  - 4.2 Final Notes [[slides]](https://simson.io/advanced-git/4.2-final_notes.html)
  - *Outro*

- Bonus Practical: GitHub Pages [[slides]](https://simson.io/advanced-git/6.1-bonus-pages.html)
- Bonus Practical: Profile Readme [[slides]](https://simson.io/advanced-git/6.2-bonus-profile-readme.html)
- Bonus Practical: git Internals [[slides]](https://simson.io/advanced-git/6.3-bonus-internals.html)

<!-- *: Since they have to be manually generated, the PDF version of slides may be slightly outdated. Please refer to [this guide](https://revealjs.com/pdf-export/), on how to export your own PDF version from the online slides. -->

### Supporting Documents

- How to Setup SSH authentication for GitHub [[PDF]](https://simson.io/intro-to-git/resources/ssh/how-to-setup-github-ssh.pdf) [[HTML]](https://malikaihle.github.io/Introduction-RStudio-Git-GitHub/SSH.html)
- [CI / CD Example Files 🤖](https://github.com/jansim/advanced-git/tree/main/resources/CI-CD-examples)
- Git Cheatsheet [[PDF]](https://simson.io/intro-to-git/resources/git-cheat-sheet-education.pdf)
  - By [GitHub Education](https://education.github.com/)

## Links

- Guides to review & refresh your knowledge
  - <https://gitimmersion.com>
  - <https://github.com/git-guides>
  - [Introduction to RStudio Git & GitHub](https://lmu-osc.github.io/Introduction-RStudio-Git-GitHub/)
  - [The Carpentries: Version Control with Git](https://swcarpentry.github.io/git-novice/)
- Pretty comprehensive guide: [Beej's Guide to Git](https://beej.us/guide/bggit/html/split/)
- The official documentation: <https://git-scm.com/doc>
- Trunk Based Development
  - <https://trunkbaseddevelopment.com/>
  - <https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development>
- Using git with data
  - [dvc](https://dvc.org/): Data Version Control
  - [git lfs](https://git-lfs.github.com/): Git Large File Storage
- If you have a problem
  - [ohshitgit.com](https://ohshitgit.com/) [(🇩🇪)](https://ohshitgit.com/de)
  - Google: Just googling your problem is often the most useful solution
- Introductory course: <http://simson.io/intro-to-git/>

## License

The contents of this course which were created by me are available under [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/). For resources where I do not own the copyright, other licenses may apply.
